In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [5]:
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [6]:
type(iris)

sklearn.utils.Bunch

In [7]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
X = iris.data

In [10]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
y = iris.target

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# one hot encoding

# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]

In [13]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [14]:
y = to_categorical(y)

In [15]:
y.shape

(150, 3)

In [16]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
# scaling the data (scales between 0 to 1)
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler_object = MinMaxScaler()

In [21]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [23]:
scaled_X_train = scaler_object.transform(X_train)

In [24]:
scaled_X_test = scaler_object.transform(X_test)

In [25]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
# keras model building
model = Sequential()
model.add(Dense(8,input_dim = 4, activation = 'relu'))
model.add(Dense(8,input_dim = 4, activation = 'relu'))
model.add(Dense(3,activation = 'softmax'))
model.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.fit(scaled_X_train,y_train,epochs = 150,verbose = 2) # 1 epoch is model running throug entire data set 1 time

Epoch 1/150
 - 1s - loss: 1.1258 - accuracy: 0.3100
Epoch 2/150
 - 0s - loss: 1.1202 - accuracy: 0.3100
Epoch 3/150
 - 0s - loss: 1.1148 - accuracy: 0.3200
Epoch 4/150
 - 0s - loss: 1.1100 - accuracy: 0.5200
Epoch 5/150
 - 0s - loss: 1.1053 - accuracy: 0.6300
Epoch 6/150
 - 0s - loss: 1.1008 - accuracy: 0.6500
Epoch 7/150
 - 0s - loss: 1.0966 - accuracy: 0.6500
Epoch 8/150
 - 0s - loss: 1.0929 - accuracy: 0.6500
Epoch 9/150
 - 0s - loss: 1.0884 - accuracy: 0.6400
Epoch 10/150
 - 0s - loss: 1.0843 - accuracy: 0.6400
Epoch 11/150
 - 0s - loss: 1.0804 - accuracy: 0.6300
Epoch 12/150
 - 0s - loss: 1.0763 - accuracy: 0.6100
Epoch 13/150
 - 0s - loss: 1.0721 - accuracy: 0.5800
Epoch 14/150
 - 0s - loss: 1.0675 - accuracy: 0.5600
Epoch 15/150
 - 0s - loss: 1.0633 - accuracy: 0.5700
Epoch 16/150
 - 0s - loss: 1.0589 - accuracy: 0.5800
Epoch 17/150
 - 0s - loss: 1.0548 - accuracy: 0.6000
Epoch 18/150
 - 0s - loss: 1.0505 - accuracy: 0.6200
Epoch 19/150
 - 0s - loss: 1.0465 - accuracy: 0.5800
Ep

In [29]:
model.predict(scaled_X_test) # gives the probabilities

array([[0.01934984, 0.4795449 , 0.5011052 ],
       [0.927834  , 0.045387  , 0.02677907],
       [0.00114861, 0.36053202, 0.6383194 ],
       [0.01765638, 0.47923088, 0.5031127 ],
       [0.00949772, 0.4395514 , 0.5509508 ],
       [0.88244593, 0.07429979, 0.04325429],
       [0.07665624, 0.49248156, 0.43086216],
       [0.00380498, 0.40288746, 0.59330755],
       [0.01156335, 0.45340657, 0.53503007],
       [0.03524674, 0.49805075, 0.46670246],
       [0.00700201, 0.43595707, 0.55704087],
       [0.89451045, 0.06788541, 0.03760419],
       [0.92794645, 0.04601707, 0.02603646],
       [0.9024984 , 0.06272859, 0.03477307],
       [0.95636725, 0.02804275, 0.01558998],
       [0.02135348, 0.46584395, 0.51280254],
       [0.00405553, 0.41107273, 0.58487177],
       [0.0357096 , 0.5062115 , 0.45807892],
       [0.02683785, 0.49499723, 0.47816494],
       [0.00433382, 0.41410837, 0.5815578 ],
       [0.9168622 , 0.05337058, 0.02976724],
       [0.0111337 , 0.46036828, 0.52849805],
       [0.

In [30]:
model.predict_classes(scaled_X_test)

array([2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 1, 2, 2, 2, 2], dtype=int64)

In [31]:
predictions = model.predict_classes(scaled_X_test)

In [35]:
y_test.argmax(axis = 1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [36]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [33]:
# model evaluation
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [38]:
print(confusion_matrix(y_test.argmax(axis = 1),predictions))

[[19  0  0]
 [ 0  5 10]
 [ 0  0 16]]


In [39]:
print(classification_report(y_test.argmax(axis = 1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.33      0.50        15
           2       0.62      1.00      0.76        16

    accuracy                           0.80        50
   macro avg       0.87      0.78      0.75        50
weighted avg       0.88      0.80      0.77        50



In [41]:
print(accuracy_score(y_test.argmax(axis = 1),predictions)*100)

80.0


In [42]:
# saving the weights of the model
model.save('myfirstmodel.h5')

In [43]:
# load the saved model
from keras.models import load_model
new_model = load_model('myfirstmodel.h5')

In [44]:
new_model.predict_classes(scaled_X_test)

array([2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 1, 2, 2, 2, 2], dtype=int64)